name       : cifar_icassp/adv_train
model      : epoch_10.pt
defense    : adv_train
seed       : 0
gpu_number : "1"
load       : False

# data

batch_size : 32

# training

lr    : 0.001
epoch : 50

# isometry

# d = 3*32*32 = 3072
# eps_inf = 0.15 => eps_2 = eps_inf * sqrt(d) = 8.3
epsilon : 8.3
eta     : 0.00001

# distillation

dist_temp : 20
teacher   : teacher.pt

# attack

attack       : fgsm    # fgsm gn pgd deep_fool cw
# 16/255 = 0.0627
budget       : 0.0627  # fgsm gn(std) pgd
perturbation : linf    # pgd
alpha        : 0.01    # pgd
max_iter     : 40      # pgd deep_fool cw
random_start : True    # pgd
