name       : cifar_icassp/resnet
model      : epoch_03.pt
defense    : baseline
seed       : 0
gpu_number : "0"
load       : False

# data

batch_size : 32

# training

lr    : 0.001
epoch : 3

# isometry

# d = 3*32*32 = 3072
# eps_inf = 16/255 => eps_2 = eps_inf * sqrt(d) = 3.5
epsilon : 3.5
eta     : 0.0000055

# distillation

dist_temp : 20
teacher   : teacher.pt

# attack

attack       : fgsm  # fgsm gn pgd deep_fool cw
budget       : 0.05  # fgsm gn(std) pgd
perturbation : linf  # pgd
alpha        : 0.1  # pgd
max_iter     : 10    # pgd deep_fool cw
random_start : True  # pgd
