name       : cifar_icassp/resnet
model      : epoch_3.pt
defense    : None
seed       : 0
gpu_number : "0"
load       : True

# test

generate   : True
clean      : False

# data

batch_size : 32

# isometry

# d = 3*32*32 = 3072
# eps_inf = 0.15 => eps_2 = eps_inf * sqrt(d) = 8.3
epsilon : 8.3

# attack

attack       : fgsm  # fgsm gn pgd deep_fool cw
budget       : 0.05  # fgsm gn(std) pgd
perturbation : linf  # pgd
alpha        : 0.01  # pgd
max_iter     : 40    # pgd deep_fool cw
random_start : True  # pgd
