name       : baseline/seed_0
model      : epoch_03.pt
dataset    : cifar
defense    : None
seed       : 0
gpu_number : "0"
load       : False

# data

batch_size : 32

# training

learning_rate    : 0.001
epochs           : 3

# annealing

epoch_thr : 1

# test

generate : False
clean    : False

# parseval

beta : 0.00001

# isometry

# d = 3*32*32 = 3072
# eps_inf = 16/255 => eps_2 = eps_inf * sqrt(d) = 3.5
epsilon : 3.5
lambda  : 0.00001

# distillation

dist_temp : 20
teacher   : teacher.pt

# attack

attack       : fgsm                 # fgsm gn pgd deep_fool cw
budget       : 0.03137254901960784  # fgsm gn(std) pgd
perturbation : linf                 # pgd
alpha        : 0.01                 # pgd
max_iter     : 10                   # pgd deep_fool cw
random_start : True                 # pgd
