name       : cifar_resnet_baseline
model      : epoch_51.pt
dataset    : cifar
defense    : None
seed       : 0
gpu_number : "0"
load       : True
autoattack : True

# model

archi     : resnet  # only lenet for MNIST
channels1 : 32
channels2 : 64
hidden    : 128

# training

learning_rate    : 0.001

# test

generate   : False
clean      : False

# data

batch_size : 32

# isometry

# d = 3*32*32 = 3072
# eps_inf = 16/255 => eps_2 = eps_inf * sqrt(d) = 3.5
epsilon : 3.5
norm    : holder

# attack

attack       : fgsm                 # fgsm gn pgd deep_fool cw
budget       : 0.03137254901960784  # fgsm gn(std) pgd
perturbation : linf                 # pgd
alpha        : 0.01                 # pgd
max_iter     : 10                   # pgd deep_fool cw
random_start : True                 # pgd

# AutoAttack

attack_norm     : Linf
eps             : 0.0156862745098039
log_path        : './outputs/log.txt'
version         : standard
